### ISSUE TITLE
use multiple collections

### ISSUE THREAD

**Issue by ddanna** [qnipp/meteor-treeview-demo#2]
Is it possible to use this with multiple collections? One collection per level of hierarchy on the tree, for example. Am I better off just starting from scratch?

**Comment by fknipp** [comment]
A feature for multiple collections is not implemented. 

If I had the time, I'd start with a new treeview component, which doesn't rely on an external JavaScript library. 

Which framework do you use? Blaze? React? Something else?

**Comment by ddanna** [comment]
I'm using Blaze for this project.

**Comment by fknipp** [comment]
In this case, you can try to alter my package to use more than one collection.

**Comment by fknipp** [comment]
… or you can use the `getNodes` function to provide your own implementation to provide the data for the nodes.
